### ISSUE TITLE
Build Problem

### ISSUE THREAD

**Issue by pratikpparikh** [cschneider/osgi-chat#2]
Can you tell me what could be wrong?  I am trying to play around with your code so i can understand how karaf and osgi can allow me to build lean microservice

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] net.lr.demo.chat.parent ............................ SUCCESS [  0.479 s]
[INFO] net.lr.demo.chat.api ............................... SUCCESS [  1.844 s]
[INFO] net.lr.demo.chat.lcd ............................... SUCCESS [  0.666 s]
[INFO] net.lr.demo.chat.irc ............................... SUCCESS [  0.652 s]
[INFO] net.lr.demo.chat.command ........................... SUCCESS [  0.341 s]
[INFO] net.lr.demo.chat.index ............................. SUCCESS [  1.521 s]
[INFO] net.lr.demo.chat.packaging ......................... SUCCESS [  0.038 s]
[INFO] net.lr.demo.chat.packaging.all ..................... FAILURE [  1.173 s]
[INFO] net.lr.demo.chat.packaging.display ................. SKIPPED
[INFO] net.lr.demo.chat.packaging.irc ..................... SKIPPED
[INFO] net.lr.demo.chat.packaging.service ................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.890 s
[INFO] Finished at: 2017-02-26T00:54:31-05:00
[INFO] Final Memory: 25M/249M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal biz.aQute.bnd:bnd-export-maven-plugin:3.3.0:export (default) on project net.lr.demo.chat.packaging.all: Default handler for Launcher-Plugin not found in biz.aQute.launcher -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal biz.aQute.bnd:bnd-export-maven-plugin:3.3.0:export (default) on project net.lr.demo.chat.packaging.all: Default handler for Launcher-Plugin not found in biz.aQute.launcher
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Default handler for Launcher-Plugin not found in biz.aQute.launcher
        at aQute.bnd.maven.export.plugin.ExportMojo.execute(ExportMojo.java:52)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.IllegalArgumentException: Default handler for Launcher-Plugin not found in biz.aQute.launcher
        at aQute.bnd.build.Project.getHandler(Project.java:2531)
        at aQute.bnd.build.Project.getProjectLauncher(Project.java:2480)
        at aQute.bnd.maven.export.plugin.ExportMojo.export(ExportMojo.java:57)
        at aQute.bnd.maven.export.plugin.ExportMojo.execute(ExportMojo.java:48)
        ... 22 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :net.lr.demo.chat.packaging.all

**Comment by pratikpparikh** [comment]
Fixed it after reading you question to bndtools issues list.
